// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:1029314881478:web:91e77d7c2be967265534c7',
    messagingSenderId: '1029314881478',
    projectId: 'invofin-3a96f',
    authDomain: 'invofin-3a96f.firebaseapp.com',
    storageBucket: 'invofin-3a96f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:1029314881478:android:35a3b01e3db9dcd15534c7',
    messagingSenderId: '1029314881478',
    projectId: 'invofin-3a96f',
    storageBucket: 'invofin-3a96f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:1029314881478:ios:68014491278105715534c7',
    messagingSenderId: '1029314881478',
    projectId: 'invofin-3a96f',
    storageBucket: 'invofin-3a96f.firebasestorage.app',
    iosBundleId: 'com.example.invoiceDiscountingApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:1029314881478:ios:68014491278105715534c7',
    messagingSenderId: '1029314881478',
    projectId: 'invofin-3a96f',
    storageBucket: 'invofin-3a96f.firebasestorage.app',
    iosBundleId: 'com.example.invoiceDiscountingApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:1029314881478:web:38a4fa0810d4d4f75534c7',
    messagingSenderId: '1029314881478',
    projectId: 'invofin-3a96f',
    authDomain: 'invofin-3a96f.firebaseapp.com',
    storageBucket: 'invofin-3a96f.firebasestorage.app',
  );
}
